### PR TITLE
fix: disable adding of questions for normal users

### LINKED ISSUE #36: Users can add questions
as stated in title

### PR DESCRIPTION
**Pull request by dsja612**
closes #36 

Also removes edit and delete buttons for normal users `(role == 'USER')`

### CODE REVIEW

**Review by LeirdaKJW — APPROVED** [review]
lgtm

File: frontend/src/components/question/modals/QuestionDetailsModal.tsx [hunk 1]
```diff
@@ -69,15 +70,20 @@ const QuestionDetailsModal: React.FC<Props> =
...
+                    Delete
+                  </Button>
+                  <Button colorScheme='cyan' mr={3} onClick={() => {
+                    closeHandler()
+                    editHandler();
+                  }} isDisabled={userRole === 'ADMIN' ? false : true}>
+                    Edit
+                  </Button>
+                </Box>
+              : null }
```
Comment (Wei-Xinn) [inline frontend/src/components/question/modals/QuestionDetailsModal.tsx]:
```suggestion
              {userRole === 'ADMIN' 
              &&
                <Box>
                  <Button colorScheme='red' mr={3} onClick={() => deleteHandler(data.id)} isDisabled={userRole === 'ADMIN' ? false : true}>
                    Delete
                  </Button>
                  <Button colorScheme='cyan' mr={3} onClick={() => {
                    closeHandler()
                    editHandler();
                  }} isDisabled={userRole === 'ADMIN' ? false : true}>
                    Edit
                  </Button>
                </Box>}
```

**Review by Wei-Xinn — CHANGES_REQUESTED** [review]

**Review by Wei-Xinn — APPROVED** [review]

File: frontend/src/components/question/modals/QuestionDetailsModal.tsx (hunk 1 above)
Comment (dsja612) [reply frontend/src/components/question/modals/QuestionDetailsModal.tsx]: implemented
